name: font-downloader # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: font-downloader
version: '10.0.0'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

layout:
  /usr/share/font-downloader:
    symlink: $SNAP/usr/share/font-downloader
    
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
slots:
  font-downloader:
    interface: dbus
    bus: session
    name: org.gustavoperedo.FontDownloader
plugs:
  home-fonts:
    interface: personal-files
    write:
      - $HOME/.local/share/fonts
  usr-share-fonts:
    interface: system-files
    read:
      - /usr/share/fonts
parts:
  font-downloader:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/GustavoPeredo/font-downloader.git
    source-tag: v10.0.0
    meson-parameters:
      - --prefix=/usr
    parse-info: [ usr/share/metainfo/org.gustavoperedo.FontDownloader.appdata.xml ]
    override-prime: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i usr/bin/fontdownloader
  
apps:
  font-downloader:
    command: usr/bin/fontdownloader
    common-id: org.gustavoperedo.FontDownloader
    extensions: [ gnome ]
    plugs:
      - home
